# MNE-CPP Travis CI for Linux and OS-X
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode7.3
      compiler: clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq                               ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qt56base qt563d qt56svg qt56serialport cppcheck; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt56/bin/qt56-env.sh                               ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5     ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt5; fi

script:
    # QA: static code analysis with CppCheck
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --enable=all -f -q -i./include/3rdParty/eigen3 -i/opt/qt56/include ./MNE ./applications ./testframes ./examples; fi
    # Build
    - qmake -r
    - make -j2

after_success:
    - echo "MNE-CPP build was successful!";

notifications:
  email:
    - christoph.dinh@mne-cpp.org
    - lorenz.esch@mne-cpp.org